# Generated by Django 6.0.2 on 2026-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customer_name_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
