# Generated by Django 6.0.2 on 2026-02-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[("Retail", "Retail"), ("Wholesale", "Wholesale")],
                        max_length=20,
                    ),
                ),
                ("mobile", models.CharField(max_length=15, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
